=begin
#spamapi

#Easily and directly scan and block spam security threats in input.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudmersiveSpamDetectionApiClient::SpamDetectionFormSubmissionAdvancedResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SpamDetectionFormSubmissionAdvancedResponse' do
  before do
    # run before each test
    @instance = CloudmersiveSpamDetectionApiClient::SpamDetectionFormSubmissionAdvancedResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SpamDetectionFormSubmissionAdvancedResponse' do
    it 'should create an instance of SpamDetectionFormSubmissionAdvancedResponse' do
      expect(@instance).to be_instance_of(CloudmersiveSpamDetectionApiClient::SpamDetectionFormSubmissionAdvancedResponse)
    end
  end
  describe 'test attribute "clean_result"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "spam_risk_level"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "contains_spam"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "contains_unsolicited_sales"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "contains_promotional_content"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "contains_phishing_attempt"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "analysis_rationale"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
