=begin
#spamapi

#Easily and directly scan and block spam security threats in input.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudmersiveSpamDetectionApiClient::SpamDetectionAdvancedRequest
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SpamDetectionAdvancedRequest' do
  before do
    # run before each test
    @instance = CloudmersiveSpamDetectionApiClient::SpamDetectionAdvancedRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SpamDetectionAdvancedRequest' do
    it 'should create an instance of SpamDetectionAdvancedRequest' do
      expect(@instance).to be_instance_of(CloudmersiveSpamDetectionApiClient::SpamDetectionAdvancedRequest)
    end
  end
  describe 'test attribute "input_string"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "model"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "allow_unsolicited_sales"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "allow_promotional_content"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "allow_phishing"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "custom_policy_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
