=begin
#spamapi

#Easily and directly scan and block spam security threats in input.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudmersiveSpamDetectionApiClient::SpamDetectionAdvancedFormField
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SpamDetectionAdvancedFormField' do
  before do
    # run before each test
    @instance = CloudmersiveSpamDetectionApiClient::SpamDetectionAdvancedFormField.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SpamDetectionAdvancedFormField' do
    it 'should create an instance of SpamDetectionAdvancedFormField' do
      expect(@instance).to be_instance_of(CloudmersiveSpamDetectionApiClient::SpamDetectionAdvancedFormField)
    end
  end
  describe 'test attribute "field_title"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "field_value"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
