=begin
#spamapi

#Easily and directly scan and block spam security threats in input.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

module CloudmersiveSpamDetectionApiClient
  VERSION = '2.4.1'
end
