=begin
#phishingapi

#Easily and directly scan and block phishing security threats.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveSpamDetectionApiClient::SpamDetectionApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SpamDetectionApi' do
  before do
    # run before each test
    @instance = CloudmersiveSpamDetectionApiClient::SpamDetectionApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SpamDetectionApi' do
    it 'should create an instance of SpamDetectionApi' do
      expect(@instance).to be_instance_of(CloudmersiveSpamDetectionApiClient::SpamDetectionApi)
    end
  end

  # unit tests for spam_detect_text_string_advanced_post
  # @param [Hash] opts the optional parameters
  # @option opts [SpamDetectionAdvancedRequest] :body 
  # @return [SpamDetectionAdvancedResponse]
  describe 'spam_detect_text_string_advanced_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
