=begin
#phishingapi

#Easily and directly scan and block phishing security threats.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

# Common files
require 'cloudmersive-spam-detection-api-client/api_client'
require 'cloudmersive-spam-detection-api-client/api_error'
require 'cloudmersive-spam-detection-api-client/version'
require 'cloudmersive-spam-detection-api-client/configuration'

# Models
require 'cloudmersive-spam-detection-api-client/models/spam_detection_advanced_request'
require 'cloudmersive-spam-detection-api-client/models/spam_detection_advanced_response'

# APIs
require 'cloudmersive-spam-detection-api-client/api/spam_detection_api'

module CloudmersiveSpamDetectionApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   CloudmersiveSpamDetectionApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
